// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basenetscenereq.proto

package com.cxy.oi.autogen;

/**
 * Protobuf type {@code basenetscenereq.BaseNetSceneReq}
 */
public final class BaseNetSceneReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:basenetscenereq.BaseNetSceneReq)
    BaseNetSceneReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BaseNetSceneReq.newBuilder() to construct.
  private BaseNetSceneReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BaseNetSceneReq() {
    netSceneReqBuff_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BaseNetSceneReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BaseNetSceneReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            netSceneType_ = input.readInt32();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            netSceneReqBuff_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cxy.oi.autogen.BaseNetSceneReqProto.internal_static_basenetscenereq_BaseNetSceneReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cxy.oi.autogen.BaseNetSceneReqProto.internal_static_basenetscenereq_BaseNetSceneReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cxy.oi.autogen.BaseNetSceneReq.class, com.cxy.oi.autogen.BaseNetSceneReq.Builder.class);
  }

  private int bitField0_;
  public static final int NET_SCENE_TYPE_FIELD_NUMBER = 1;
  private int netSceneType_;
  /**
   * <code>optional int32 net_scene_type = 1;</code>
   * @return Whether the netSceneType field is set.
   */
  @java.lang.Override
  public boolean hasNetSceneType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 net_scene_type = 1;</code>
   * @return The netSceneType.
   */
  @java.lang.Override
  public int getNetSceneType() {
    return netSceneType_;
  }

  public static final int NET_SCENE_REQ_BUFF_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString netSceneReqBuff_;
  /**
   * <code>optional bytes net_scene_req_buff = 2;</code>
   * @return Whether the netSceneReqBuff field is set.
   */
  @java.lang.Override
  public boolean hasNetSceneReqBuff() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bytes net_scene_req_buff = 2;</code>
   * @return The netSceneReqBuff.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNetSceneReqBuff() {
    return netSceneReqBuff_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, netSceneType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, netSceneReqBuff_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, netSceneType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, netSceneReqBuff_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cxy.oi.autogen.BaseNetSceneReq)) {
      return super.equals(obj);
    }
    com.cxy.oi.autogen.BaseNetSceneReq other = (com.cxy.oi.autogen.BaseNetSceneReq) obj;

    if (hasNetSceneType() != other.hasNetSceneType()) return false;
    if (hasNetSceneType()) {
      if (getNetSceneType()
          != other.getNetSceneType()) return false;
    }
    if (hasNetSceneReqBuff() != other.hasNetSceneReqBuff()) return false;
    if (hasNetSceneReqBuff()) {
      if (!getNetSceneReqBuff()
          .equals(other.getNetSceneReqBuff())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNetSceneType()) {
      hash = (37 * hash) + NET_SCENE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getNetSceneType();
    }
    if (hasNetSceneReqBuff()) {
      hash = (37 * hash) + NET_SCENE_REQ_BUFF_FIELD_NUMBER;
      hash = (53 * hash) + getNetSceneReqBuff().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cxy.oi.autogen.BaseNetSceneReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.BaseNetSceneReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cxy.oi.autogen.BaseNetSceneReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code basenetscenereq.BaseNetSceneReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:basenetscenereq.BaseNetSceneReq)
      com.cxy.oi.autogen.BaseNetSceneReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cxy.oi.autogen.BaseNetSceneReqProto.internal_static_basenetscenereq_BaseNetSceneReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cxy.oi.autogen.BaseNetSceneReqProto.internal_static_basenetscenereq_BaseNetSceneReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cxy.oi.autogen.BaseNetSceneReq.class, com.cxy.oi.autogen.BaseNetSceneReq.Builder.class);
    }

    // Construct using com.cxy.oi.autogen.BaseNetSceneReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      netSceneType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      netSceneReqBuff_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cxy.oi.autogen.BaseNetSceneReqProto.internal_static_basenetscenereq_BaseNetSceneReq_descriptor;
    }

    @java.lang.Override
    public com.cxy.oi.autogen.BaseNetSceneReq getDefaultInstanceForType() {
      return com.cxy.oi.autogen.BaseNetSceneReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.cxy.oi.autogen.BaseNetSceneReq build() {
      com.cxy.oi.autogen.BaseNetSceneReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cxy.oi.autogen.BaseNetSceneReq buildPartial() {
      com.cxy.oi.autogen.BaseNetSceneReq result = new com.cxy.oi.autogen.BaseNetSceneReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.netSceneType_ = netSceneType_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.netSceneReqBuff_ = netSceneReqBuff_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cxy.oi.autogen.BaseNetSceneReq) {
        return mergeFrom((com.cxy.oi.autogen.BaseNetSceneReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cxy.oi.autogen.BaseNetSceneReq other) {
      if (other == com.cxy.oi.autogen.BaseNetSceneReq.getDefaultInstance()) return this;
      if (other.hasNetSceneType()) {
        setNetSceneType(other.getNetSceneType());
      }
      if (other.hasNetSceneReqBuff()) {
        setNetSceneReqBuff(other.getNetSceneReqBuff());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cxy.oi.autogen.BaseNetSceneReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cxy.oi.autogen.BaseNetSceneReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int netSceneType_ ;
    /**
     * <code>optional int32 net_scene_type = 1;</code>
     * @return Whether the netSceneType field is set.
     */
    @java.lang.Override
    public boolean hasNetSceneType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 net_scene_type = 1;</code>
     * @return The netSceneType.
     */
    @java.lang.Override
    public int getNetSceneType() {
      return netSceneType_;
    }
    /**
     * <code>optional int32 net_scene_type = 1;</code>
     * @param value The netSceneType to set.
     * @return This builder for chaining.
     */
    public Builder setNetSceneType(int value) {
      bitField0_ |= 0x00000001;
      netSceneType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 net_scene_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetSceneType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      netSceneType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString netSceneReqBuff_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes net_scene_req_buff = 2;</code>
     * @return Whether the netSceneReqBuff field is set.
     */
    @java.lang.Override
    public boolean hasNetSceneReqBuff() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes net_scene_req_buff = 2;</code>
     * @return The netSceneReqBuff.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNetSceneReqBuff() {
      return netSceneReqBuff_;
    }
    /**
     * <code>optional bytes net_scene_req_buff = 2;</code>
     * @param value The netSceneReqBuff to set.
     * @return This builder for chaining.
     */
    public Builder setNetSceneReqBuff(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      netSceneReqBuff_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes net_scene_req_buff = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetSceneReqBuff() {
      bitField0_ = (bitField0_ & ~0x00000002);
      netSceneReqBuff_ = getDefaultInstance().getNetSceneReqBuff();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:basenetscenereq.BaseNetSceneReq)
  }

  // @@protoc_insertion_point(class_scope:basenetscenereq.BaseNetSceneReq)
  private static final com.cxy.oi.autogen.BaseNetSceneReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cxy.oi.autogen.BaseNetSceneReq();
  }

  public static com.cxy.oi.autogen.BaseNetSceneReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<BaseNetSceneReq>
      PARSER = new com.google.protobuf.AbstractParser<BaseNetSceneReq>() {
    @java.lang.Override
    public BaseNetSceneReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BaseNetSceneReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BaseNetSceneReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BaseNetSceneReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cxy.oi.autogen.BaseNetSceneReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

