// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basenetscenereq.proto

package com.cxy.oi.autogen;

public final class BaseNetSceneReqProto {
  private BaseNetSceneReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_basenetscenereq_BaseNetSceneReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_basenetscenereq_BaseNetSceneReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025basenetscenereq.proto\022\017basenetscenereq" +
      "\"E\n\017BaseNetSceneReq\022\026\n\016net_scene_type\030\001 " +
      "\001(\005\022\032\n\022net_scene_req_buff\030\002 \001(\014B,\n\022com.c" +
      "xy.oi.autogenB\024BaseNetSceneReqProtoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_basenetscenereq_BaseNetSceneReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_basenetscenereq_BaseNetSceneReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_basenetscenereq_BaseNetSceneReq_descriptor,
        new java.lang.String[] { "NetSceneType", "NetSceneReqBuff", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
