// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenegethotsearch.proto

package com.cxy.oi.autogen;

public interface NetSceneGetHotSearchRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netscenegethotsearch.NetSceneGetHotSearchResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
   */
  java.util.List<com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem> 
      getHotSearchItemsList();
  /**
   * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
   */
  com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem getHotSearchItems(int index);
  /**
   * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
   */
  int getHotSearchItemsCount();
  /**
   * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
   */
  java.util.List<? extends com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItemOrBuilder> 
      getHotSearchItemsOrBuilderList();
  /**
   * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
   */
  com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItemOrBuilder getHotSearchItemsOrBuilder(
      int index);
}
