// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenegettrainprogress.proto

package com.cxy.oi.autogen;

public interface NetSceneGetTrainProgressReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netscenegettrainprogress.NetSceneGetTrainProgressReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * no req body, this is for padding.
   * </pre>
   *
   * <code>optional bool nop = 1;</code>
   * @return Whether the nop field is set.
   */
  boolean hasNop();
  /**
   * <pre>
   * no req body, this is for padding.
   * </pre>
   *
   * <code>optional bool nop = 1;</code>
   * @return The nop.
   */
  boolean getNop();
}
