// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netsceneuploadavatar.proto

package com.cxy.oi.autogen;

public interface NetSceneUploadAvatarReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netsceneuploadavatar.NetSceneUploadAvatarReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 usr_id = 1;</code>
   * @return Whether the usrId field is set.
   */
  boolean hasUsrId();
  /**
   * <code>optional uint32 usr_id = 1;</code>
   * @return The usrId.
   */
  int getUsrId();

  /**
   * <code>optional bytes avatar_img_bytes = 2;</code>
   * @return Whether the avatarImgBytes field is set.
   */
  boolean hasAvatarImgBytes();
  /**
   * <code>optional bytes avatar_img_bytes = 2;</code>
   * @return The avatarImgBytes.
   */
  com.google.protobuf.ByteString getAvatarImgBytes();
}
