// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netsceneregister.proto

package com.cxy.oi.autogen;

public interface NetSceneRegisterRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netsceneregister.NetSceneRegisterResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 usr_id = 1;</code>
   * @return Whether the usrId field is set.
   */
  boolean hasUsrId();
  /**
   * <code>optional uint32 usr_id = 1;</code>
   * @return The usrId.
   */
  int getUsrId();
}
