// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenequeryimg.proto

package com.cxy.oi.autogen;

public final class Netscenequeryimg {
  private Netscenequeryimg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netscenequeryimg_NetSceneQueryImgReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netscenequeryimg_NetSceneQueryImgReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netscenequeryimg_NetSceneQueryImgResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netscenequeryimg_NetSceneQueryImgResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026netscenequeryimg.proto\022\020netscenequeryi" +
      "mg\"(\n\023NetSceneQueryImgReq\022\021\n\timg_bytes\030\001" +
      " \002(\014\"\270\001\n\024NetSceneQueryImgResp\022I\n\titem_ty" +
      "pe\030\001 \002(\0162/.netscenequeryimg.NetSceneQuer" +
      "yImgResp.ItemType:\005PLANT\022\021\n\titem_name\030\002 " +
      "\002(\t\022\021\n\titem_desc\030\003 \002(\t\"/\n\010ItemType\022\t\n\005PL" +
      "ANT\020\000\022\n\n\006ANIMAL\020\001\022\014\n\010LANDMARK\020\002B\026\n\022com.c" +
      "xy.oi.autogenP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_netscenequeryimg_NetSceneQueryImgReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netscenequeryimg_NetSceneQueryImgReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netscenequeryimg_NetSceneQueryImgReq_descriptor,
        new java.lang.String[] { "ImgBytes", });
    internal_static_netscenequeryimg_NetSceneQueryImgResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_netscenequeryimg_NetSceneQueryImgResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netscenequeryimg_NetSceneQueryImgResp_descriptor,
        new java.lang.String[] { "ItemType", "ItemName", "ItemDesc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
