// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netsceneregister.proto

package com.cxy.oi.autogen;

public final class NetSceneRegisterProto {
  private NetSceneRegisterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netsceneregister_NetSceneRegisterReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netsceneregister_NetSceneRegisterReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netsceneregister_NetSceneRegisterResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netsceneregister_NetSceneRegisterResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026netsceneregister.proto\022\020netsceneregist" +
      "er\"\"\n\023NetSceneRegisterReq\022\013\n\003nop\030\001 \001(\010\"&" +
      "\n\024NetSceneRegisterResp\022\016\n\006usr_id\030\001 \001(\rB-" +
      "\n\022com.cxy.oi.autogenB\025NetSceneRegisterPr" +
      "otoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_netsceneregister_NetSceneRegisterReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netsceneregister_NetSceneRegisterReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netsceneregister_NetSceneRegisterReq_descriptor,
        new java.lang.String[] { "Nop", });
    internal_static_netsceneregister_NetSceneRegisterResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_netsceneregister_NetSceneRegisterResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netsceneregister_NetSceneRegisterResp_descriptor,
        new java.lang.String[] { "UsrId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
