// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenegettrainprogress.proto

package com.cxy.oi.autogen;

/**
 * Protobuf type {@code netscenegettrainprogress.NetSceneGetTrainProgressResp}
 */
public final class NetSceneGetTrainProgressResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:netscenegettrainprogress.NetSceneGetTrainProgressResp)
    NetSceneGetTrainProgressRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetSceneGetTrainProgressResp.newBuilder() to construct.
  private NetSceneGetTrainProgressResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetSceneGetTrainProgressResp() {
    hitRates_ = emptyFloatList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NetSceneGetTrainProgressResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NetSceneGetTrainProgressResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            isRunning_ = input.readBool();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            currEpoch_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            totalEpoch_ = input.readInt32();
            break;
          }
          case 37: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              hitRates_ = newFloatList();
              mutable_bitField0_ |= 0x00000008;
            }
            hitRates_.addFloat(input.readFloat());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
              hitRates_ = newFloatList();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              hitRates_.addFloat(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        hitRates_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cxy.oi.autogen.NetSceneGetTrainProgressProto.internal_static_netscenegettrainprogress_NetSceneGetTrainProgressResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cxy.oi.autogen.NetSceneGetTrainProgressProto.internal_static_netscenegettrainprogress_NetSceneGetTrainProgressResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cxy.oi.autogen.NetSceneGetTrainProgressResp.class, com.cxy.oi.autogen.NetSceneGetTrainProgressResp.Builder.class);
  }

  private int bitField0_;
  public static final int IS_RUNNING_FIELD_NUMBER = 1;
  private boolean isRunning_;
  /**
   * <code>optional bool is_running = 1;</code>
   * @return Whether the isRunning field is set.
   */
  @java.lang.Override
  public boolean hasIsRunning() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bool is_running = 1;</code>
   * @return The isRunning.
   */
  @java.lang.Override
  public boolean getIsRunning() {
    return isRunning_;
  }

  public static final int CURR_EPOCH_FIELD_NUMBER = 2;
  private int currEpoch_;
  /**
   * <code>optional int32 curr_epoch = 2;</code>
   * @return Whether the currEpoch field is set.
   */
  @java.lang.Override
  public boolean hasCurrEpoch() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 curr_epoch = 2;</code>
   * @return The currEpoch.
   */
  @java.lang.Override
  public int getCurrEpoch() {
    return currEpoch_;
  }

  public static final int TOTAL_EPOCH_FIELD_NUMBER = 3;
  private int totalEpoch_;
  /**
   * <code>optional int32 total_epoch = 3;</code>
   * @return Whether the totalEpoch field is set.
   */
  @java.lang.Override
  public boolean hasTotalEpoch() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 total_epoch = 3;</code>
   * @return The totalEpoch.
   */
  @java.lang.Override
  public int getTotalEpoch() {
    return totalEpoch_;
  }

  public static final int HIT_RATES_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.FloatList hitRates_;
  /**
   * <code>repeated float hit_rates = 4;</code>
   * @return A list containing the hitRates.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getHitRatesList() {
    return hitRates_;
  }
  /**
   * <code>repeated float hit_rates = 4;</code>
   * @return The count of hitRates.
   */
  public int getHitRatesCount() {
    return hitRates_.size();
  }
  /**
   * <code>repeated float hit_rates = 4;</code>
   * @param index The index of the element to return.
   * @return The hitRates at the given index.
   */
  public float getHitRates(int index) {
    return hitRates_.getFloat(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, isRunning_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, currEpoch_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, totalEpoch_);
    }
    for (int i = 0; i < hitRates_.size(); i++) {
      output.writeFloat(4, hitRates_.getFloat(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isRunning_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, currEpoch_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalEpoch_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getHitRatesList().size();
      size += dataSize;
      size += 1 * getHitRatesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cxy.oi.autogen.NetSceneGetTrainProgressResp)) {
      return super.equals(obj);
    }
    com.cxy.oi.autogen.NetSceneGetTrainProgressResp other = (com.cxy.oi.autogen.NetSceneGetTrainProgressResp) obj;

    if (hasIsRunning() != other.hasIsRunning()) return false;
    if (hasIsRunning()) {
      if (getIsRunning()
          != other.getIsRunning()) return false;
    }
    if (hasCurrEpoch() != other.hasCurrEpoch()) return false;
    if (hasCurrEpoch()) {
      if (getCurrEpoch()
          != other.getCurrEpoch()) return false;
    }
    if (hasTotalEpoch() != other.hasTotalEpoch()) return false;
    if (hasTotalEpoch()) {
      if (getTotalEpoch()
          != other.getTotalEpoch()) return false;
    }
    if (!getHitRatesList()
        .equals(other.getHitRatesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIsRunning()) {
      hash = (37 * hash) + IS_RUNNING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsRunning());
    }
    if (hasCurrEpoch()) {
      hash = (37 * hash) + CURR_EPOCH_FIELD_NUMBER;
      hash = (53 * hash) + getCurrEpoch();
    }
    if (hasTotalEpoch()) {
      hash = (37 * hash) + TOTAL_EPOCH_FIELD_NUMBER;
      hash = (53 * hash) + getTotalEpoch();
    }
    if (getHitRatesCount() > 0) {
      hash = (37 * hash) + HIT_RATES_FIELD_NUMBER;
      hash = (53 * hash) + getHitRatesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cxy.oi.autogen.NetSceneGetTrainProgressResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code netscenegettrainprogress.NetSceneGetTrainProgressResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:netscenegettrainprogress.NetSceneGetTrainProgressResp)
      com.cxy.oi.autogen.NetSceneGetTrainProgressRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cxy.oi.autogen.NetSceneGetTrainProgressProto.internal_static_netscenegettrainprogress_NetSceneGetTrainProgressResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cxy.oi.autogen.NetSceneGetTrainProgressProto.internal_static_netscenegettrainprogress_NetSceneGetTrainProgressResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cxy.oi.autogen.NetSceneGetTrainProgressResp.class, com.cxy.oi.autogen.NetSceneGetTrainProgressResp.Builder.class);
    }

    // Construct using com.cxy.oi.autogen.NetSceneGetTrainProgressResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isRunning_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      currEpoch_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      totalEpoch_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      hitRates_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cxy.oi.autogen.NetSceneGetTrainProgressProto.internal_static_netscenegettrainprogress_NetSceneGetTrainProgressResp_descriptor;
    }

    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneGetTrainProgressResp getDefaultInstanceForType() {
      return com.cxy.oi.autogen.NetSceneGetTrainProgressResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneGetTrainProgressResp build() {
      com.cxy.oi.autogen.NetSceneGetTrainProgressResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneGetTrainProgressResp buildPartial() {
      com.cxy.oi.autogen.NetSceneGetTrainProgressResp result = new com.cxy.oi.autogen.NetSceneGetTrainProgressResp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isRunning_ = isRunning_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.currEpoch_ = currEpoch_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalEpoch_ = totalEpoch_;
        to_bitField0_ |= 0x00000004;
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        hitRates_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.hitRates_ = hitRates_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cxy.oi.autogen.NetSceneGetTrainProgressResp) {
        return mergeFrom((com.cxy.oi.autogen.NetSceneGetTrainProgressResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cxy.oi.autogen.NetSceneGetTrainProgressResp other) {
      if (other == com.cxy.oi.autogen.NetSceneGetTrainProgressResp.getDefaultInstance()) return this;
      if (other.hasIsRunning()) {
        setIsRunning(other.getIsRunning());
      }
      if (other.hasCurrEpoch()) {
        setCurrEpoch(other.getCurrEpoch());
      }
      if (other.hasTotalEpoch()) {
        setTotalEpoch(other.getTotalEpoch());
      }
      if (!other.hitRates_.isEmpty()) {
        if (hitRates_.isEmpty()) {
          hitRates_ = other.hitRates_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureHitRatesIsMutable();
          hitRates_.addAll(other.hitRates_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cxy.oi.autogen.NetSceneGetTrainProgressResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cxy.oi.autogen.NetSceneGetTrainProgressResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean isRunning_ ;
    /**
     * <code>optional bool is_running = 1;</code>
     * @return Whether the isRunning field is set.
     */
    @java.lang.Override
    public boolean hasIsRunning() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool is_running = 1;</code>
     * @return The isRunning.
     */
    @java.lang.Override
    public boolean getIsRunning() {
      return isRunning_;
    }
    /**
     * <code>optional bool is_running = 1;</code>
     * @param value The isRunning to set.
     * @return This builder for chaining.
     */
    public Builder setIsRunning(boolean value) {
      bitField0_ |= 0x00000001;
      isRunning_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_running = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsRunning() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isRunning_ = false;
      onChanged();
      return this;
    }

    private int currEpoch_ ;
    /**
     * <code>optional int32 curr_epoch = 2;</code>
     * @return Whether the currEpoch field is set.
     */
    @java.lang.Override
    public boolean hasCurrEpoch() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 curr_epoch = 2;</code>
     * @return The currEpoch.
     */
    @java.lang.Override
    public int getCurrEpoch() {
      return currEpoch_;
    }
    /**
     * <code>optional int32 curr_epoch = 2;</code>
     * @param value The currEpoch to set.
     * @return This builder for chaining.
     */
    public Builder setCurrEpoch(int value) {
      bitField0_ |= 0x00000002;
      currEpoch_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 curr_epoch = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrEpoch() {
      bitField0_ = (bitField0_ & ~0x00000002);
      currEpoch_ = 0;
      onChanged();
      return this;
    }

    private int totalEpoch_ ;
    /**
     * <code>optional int32 total_epoch = 3;</code>
     * @return Whether the totalEpoch field is set.
     */
    @java.lang.Override
    public boolean hasTotalEpoch() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 total_epoch = 3;</code>
     * @return The totalEpoch.
     */
    @java.lang.Override
    public int getTotalEpoch() {
      return totalEpoch_;
    }
    /**
     * <code>optional int32 total_epoch = 3;</code>
     * @param value The totalEpoch to set.
     * @return This builder for chaining.
     */
    public Builder setTotalEpoch(int value) {
      bitField0_ |= 0x00000004;
      totalEpoch_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 total_epoch = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalEpoch() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalEpoch_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList hitRates_ = emptyFloatList();
    private void ensureHitRatesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        hitRates_ = mutableCopy(hitRates_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated float hit_rates = 4;</code>
     * @return A list containing the hitRates.
     */
    public java.util.List<java.lang.Float>
        getHitRatesList() {
      return ((bitField0_ & 0x00000008) != 0) ?
               java.util.Collections.unmodifiableList(hitRates_) : hitRates_;
    }
    /**
     * <code>repeated float hit_rates = 4;</code>
     * @return The count of hitRates.
     */
    public int getHitRatesCount() {
      return hitRates_.size();
    }
    /**
     * <code>repeated float hit_rates = 4;</code>
     * @param index The index of the element to return.
     * @return The hitRates at the given index.
     */
    public float getHitRates(int index) {
      return hitRates_.getFloat(index);
    }
    /**
     * <code>repeated float hit_rates = 4;</code>
     * @param index The index to set the value at.
     * @param value The hitRates to set.
     * @return This builder for chaining.
     */
    public Builder setHitRates(
        int index, float value) {
      ensureHitRatesIsMutable();
      hitRates_.setFloat(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float hit_rates = 4;</code>
     * @param value The hitRates to add.
     * @return This builder for chaining.
     */
    public Builder addHitRates(float value) {
      ensureHitRatesIsMutable();
      hitRates_.addFloat(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float hit_rates = 4;</code>
     * @param values The hitRates to add.
     * @return This builder for chaining.
     */
    public Builder addAllHitRates(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureHitRatesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, hitRates_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float hit_rates = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHitRates() {
      hitRates_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:netscenegettrainprogress.NetSceneGetTrainProgressResp)
  }

  // @@protoc_insertion_point(class_scope:netscenegettrainprogress.NetSceneGetTrainProgressResp)
  private static final com.cxy.oi.autogen.NetSceneGetTrainProgressResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cxy.oi.autogen.NetSceneGetTrainProgressResp();
  }

  public static com.cxy.oi.autogen.NetSceneGetTrainProgressResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<NetSceneGetTrainProgressResp>
      PARSER = new com.google.protobuf.AbstractParser<NetSceneGetTrainProgressResp>() {
    @java.lang.Override
    public NetSceneGetTrainProgressResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NetSceneGetTrainProgressResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NetSceneGetTrainProgressResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetSceneGetTrainProgressResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cxy.oi.autogen.NetSceneGetTrainProgressResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

