// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenegettrainprogress.proto

package com.cxy.oi.autogen;

public interface NetSceneGetTrainProgressRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netscenegettrainprogress.NetSceneGetTrainProgressResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool is_running = 1;</code>
   * @return Whether the isRunning field is set.
   */
  boolean hasIsRunning();
  /**
   * <code>optional bool is_running = 1;</code>
   * @return The isRunning.
   */
  boolean getIsRunning();

  /**
   * <code>optional int32 curr_epoch = 2;</code>
   * @return Whether the currEpoch field is set.
   */
  boolean hasCurrEpoch();
  /**
   * <code>optional int32 curr_epoch = 2;</code>
   * @return The currEpoch.
   */
  int getCurrEpoch();

  /**
   * <code>optional int32 total_epoch = 3;</code>
   * @return Whether the totalEpoch field is set.
   */
  boolean hasTotalEpoch();
  /**
   * <code>optional int32 total_epoch = 3;</code>
   * @return The totalEpoch.
   */
  int getTotalEpoch();

  /**
   * <code>repeated float hit_rates = 4;</code>
   * @return A list containing the hitRates.
   */
  java.util.List<java.lang.Float> getHitRatesList();
  /**
   * <code>repeated float hit_rates = 4;</code>
   * @return The count of hitRates.
   */
  int getHitRatesCount();
  /**
   * <code>repeated float hit_rates = 4;</code>
   * @param index The index of the element to return.
   * @return The hitRates at the given index.
   */
  float getHitRates(int index);
}
