// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenequeryimg.proto

package com.cxy.oi.autogen;

/**
 * Protobuf type {@code netscenequeryimg.NetSceneQueryImgResp}
 */
public final class NetSceneQueryImgResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:netscenequeryimg.NetSceneQueryImgResp)
    NetSceneQueryImgRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetSceneQueryImgResp.newBuilder() to construct.
  private NetSceneQueryImgResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetSceneQueryImgResp() {
    itemType_ = 0;
    itemName_ = "";
    itemDesc_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NetSceneQueryImgResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NetSceneQueryImgResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType value = com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              itemType_ = rawValue;
            }
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            itemName_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            itemDesc_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cxy.oi.autogen.Netscenequeryimg.internal_static_netscenequeryimg_NetSceneQueryImgResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cxy.oi.autogen.Netscenequeryimg.internal_static_netscenequeryimg_NetSceneQueryImgResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cxy.oi.autogen.NetSceneQueryImgResp.class, com.cxy.oi.autogen.NetSceneQueryImgResp.Builder.class);
  }

  /**
   * Protobuf enum {@code netscenequeryimg.NetSceneQueryImgResp.ItemType}
   */
  public enum ItemType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PLANT = 0;</code>
     */
    PLANT(0),
    /**
     * <code>ANIMAL = 1;</code>
     */
    ANIMAL(1),
    /**
     * <code>LANDMARK = 2;</code>
     */
    LANDMARK(2),
    ;

    /**
     * <code>PLANT = 0;</code>
     */
    public static final int PLANT_VALUE = 0;
    /**
     * <code>ANIMAL = 1;</code>
     */
    public static final int ANIMAL_VALUE = 1;
    /**
     * <code>LANDMARK = 2;</code>
     */
    public static final int LANDMARK_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ItemType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ItemType forNumber(int value) {
      switch (value) {
        case 0: return PLANT;
        case 1: return ANIMAL;
        case 2: return LANDMARK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ItemType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ItemType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ItemType>() {
            public ItemType findValueByNumber(int number) {
              return ItemType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.cxy.oi.autogen.NetSceneQueryImgResp.getDescriptor().getEnumTypes().get(0);
    }

    private static final ItemType[] VALUES = values();

    public static ItemType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ItemType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:netscenequeryimg.NetSceneQueryImgResp.ItemType)
  }

  private int bitField0_;
  public static final int ITEM_TYPE_FIELD_NUMBER = 1;
  private int itemType_;
  /**
   * <code>required .netscenequeryimg.NetSceneQueryImgResp.ItemType item_type = 1 [default = PLANT];</code>
   * @return Whether the itemType field is set.
   */
  @java.lang.Override public boolean hasItemType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .netscenequeryimg.NetSceneQueryImgResp.ItemType item_type = 1 [default = PLANT];</code>
   * @return The itemType.
   */
  @java.lang.Override public com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType getItemType() {
    @SuppressWarnings("deprecation")
    com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType result = com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType.valueOf(itemType_);
    return result == null ? com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType.PLANT : result;
  }

  public static final int ITEM_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object itemName_;
  /**
   * <code>required string item_name = 2;</code>
   * @return Whether the itemName field is set.
   */
  @java.lang.Override
  public boolean hasItemName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required string item_name = 2;</code>
   * @return The itemName.
   */
  @java.lang.Override
  public java.lang.String getItemName() {
    java.lang.Object ref = itemName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        itemName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string item_name = 2;</code>
   * @return The bytes for itemName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getItemNameBytes() {
    java.lang.Object ref = itemName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      itemName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEM_DESC_FIELD_NUMBER = 3;
  private volatile java.lang.Object itemDesc_;
  /**
   * <code>required string item_desc = 3;</code>
   * @return Whether the itemDesc field is set.
   */
  @java.lang.Override
  public boolean hasItemDesc() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>required string item_desc = 3;</code>
   * @return The itemDesc.
   */
  @java.lang.Override
  public java.lang.String getItemDesc() {
    java.lang.Object ref = itemDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        itemDesc_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string item_desc = 3;</code>
   * @return The bytes for itemDesc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getItemDescBytes() {
    java.lang.Object ref = itemDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      itemDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasItemType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasItemName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasItemDesc()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, itemType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, itemName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, itemDesc_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, itemType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, itemName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, itemDesc_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cxy.oi.autogen.NetSceneQueryImgResp)) {
      return super.equals(obj);
    }
    com.cxy.oi.autogen.NetSceneQueryImgResp other = (com.cxy.oi.autogen.NetSceneQueryImgResp) obj;

    if (hasItemType() != other.hasItemType()) return false;
    if (hasItemType()) {
      if (itemType_ != other.itemType_) return false;
    }
    if (hasItemName() != other.hasItemName()) return false;
    if (hasItemName()) {
      if (!getItemName()
          .equals(other.getItemName())) return false;
    }
    if (hasItemDesc() != other.hasItemDesc()) return false;
    if (hasItemDesc()) {
      if (!getItemDesc()
          .equals(other.getItemDesc())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasItemType()) {
      hash = (37 * hash) + ITEM_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + itemType_;
    }
    if (hasItemName()) {
      hash = (37 * hash) + ITEM_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getItemName().hashCode();
    }
    if (hasItemDesc()) {
      hash = (37 * hash) + ITEM_DESC_FIELD_NUMBER;
      hash = (53 * hash) + getItemDesc().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.NetSceneQueryImgResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cxy.oi.autogen.NetSceneQueryImgResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code netscenequeryimg.NetSceneQueryImgResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:netscenequeryimg.NetSceneQueryImgResp)
      com.cxy.oi.autogen.NetSceneQueryImgRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cxy.oi.autogen.Netscenequeryimg.internal_static_netscenequeryimg_NetSceneQueryImgResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cxy.oi.autogen.Netscenequeryimg.internal_static_netscenequeryimg_NetSceneQueryImgResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cxy.oi.autogen.NetSceneQueryImgResp.class, com.cxy.oi.autogen.NetSceneQueryImgResp.Builder.class);
    }

    // Construct using com.cxy.oi.autogen.NetSceneQueryImgResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      itemType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      itemName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      itemDesc_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cxy.oi.autogen.Netscenequeryimg.internal_static_netscenequeryimg_NetSceneQueryImgResp_descriptor;
    }

    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneQueryImgResp getDefaultInstanceForType() {
      return com.cxy.oi.autogen.NetSceneQueryImgResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneQueryImgResp build() {
      com.cxy.oi.autogen.NetSceneQueryImgResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneQueryImgResp buildPartial() {
      com.cxy.oi.autogen.NetSceneQueryImgResp result = new com.cxy.oi.autogen.NetSceneQueryImgResp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.itemType_ = itemType_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.itemName_ = itemName_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.itemDesc_ = itemDesc_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cxy.oi.autogen.NetSceneQueryImgResp) {
        return mergeFrom((com.cxy.oi.autogen.NetSceneQueryImgResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cxy.oi.autogen.NetSceneQueryImgResp other) {
      if (other == com.cxy.oi.autogen.NetSceneQueryImgResp.getDefaultInstance()) return this;
      if (other.hasItemType()) {
        setItemType(other.getItemType());
      }
      if (other.hasItemName()) {
        bitField0_ |= 0x00000002;
        itemName_ = other.itemName_;
        onChanged();
      }
      if (other.hasItemDesc()) {
        bitField0_ |= 0x00000004;
        itemDesc_ = other.itemDesc_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasItemType()) {
        return false;
      }
      if (!hasItemName()) {
        return false;
      }
      if (!hasItemDesc()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cxy.oi.autogen.NetSceneQueryImgResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cxy.oi.autogen.NetSceneQueryImgResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int itemType_ = 0;
    /**
     * <code>required .netscenequeryimg.NetSceneQueryImgResp.ItemType item_type = 1 [default = PLANT];</code>
     * @return Whether the itemType field is set.
     */
    @java.lang.Override public boolean hasItemType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .netscenequeryimg.NetSceneQueryImgResp.ItemType item_type = 1 [default = PLANT];</code>
     * @return The itemType.
     */
    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType getItemType() {
      @SuppressWarnings("deprecation")
      com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType result = com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType.valueOf(itemType_);
      return result == null ? com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType.PLANT : result;
    }
    /**
     * <code>required .netscenequeryimg.NetSceneQueryImgResp.ItemType item_type = 1 [default = PLANT];</code>
     * @param value The itemType to set.
     * @return This builder for chaining.
     */
    public Builder setItemType(com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      itemType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .netscenequeryimg.NetSceneQueryImgResp.ItemType item_type = 1 [default = PLANT];</code>
     * @return This builder for chaining.
     */
    public Builder clearItemType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      itemType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object itemName_ = "";
    /**
     * <code>required string item_name = 2;</code>
     * @return Whether the itemName field is set.
     */
    public boolean hasItemName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string item_name = 2;</code>
     * @return The itemName.
     */
    public java.lang.String getItemName() {
      java.lang.Object ref = itemName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string item_name = 2;</code>
     * @return The bytes for itemName.
     */
    public com.google.protobuf.ByteString
        getItemNameBytes() {
      java.lang.Object ref = itemName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string item_name = 2;</code>
     * @param value The itemName to set.
     * @return This builder for chaining.
     */
    public Builder setItemName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      itemName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string item_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      itemName_ = getDefaultInstance().getItemName();
      onChanged();
      return this;
    }
    /**
     * <code>required string item_name = 2;</code>
     * @param value The bytes for itemName to set.
     * @return This builder for chaining.
     */
    public Builder setItemNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      itemName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object itemDesc_ = "";
    /**
     * <code>required string item_desc = 3;</code>
     * @return Whether the itemDesc field is set.
     */
    public boolean hasItemDesc() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string item_desc = 3;</code>
     * @return The itemDesc.
     */
    public java.lang.String getItemDesc() {
      java.lang.Object ref = itemDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemDesc_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string item_desc = 3;</code>
     * @return The bytes for itemDesc.
     */
    public com.google.protobuf.ByteString
        getItemDescBytes() {
      java.lang.Object ref = itemDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string item_desc = 3;</code>
     * @param value The itemDesc to set.
     * @return This builder for chaining.
     */
    public Builder setItemDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      itemDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string item_desc = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemDesc() {
      bitField0_ = (bitField0_ & ~0x00000004);
      itemDesc_ = getDefaultInstance().getItemDesc();
      onChanged();
      return this;
    }
    /**
     * <code>required string item_desc = 3;</code>
     * @param value The bytes for itemDesc to set.
     * @return This builder for chaining.
     */
    public Builder setItemDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      itemDesc_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:netscenequeryimg.NetSceneQueryImgResp)
  }

  // @@protoc_insertion_point(class_scope:netscenequeryimg.NetSceneQueryImgResp)
  private static final com.cxy.oi.autogen.NetSceneQueryImgResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cxy.oi.autogen.NetSceneQueryImgResp();
  }

  public static com.cxy.oi.autogen.NetSceneQueryImgResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<NetSceneQueryImgResp>
      PARSER = new com.google.protobuf.AbstractParser<NetSceneQueryImgResp>() {
    @java.lang.Override
    public NetSceneQueryImgResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NetSceneQueryImgResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NetSceneQueryImgResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetSceneQueryImgResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cxy.oi.autogen.NetSceneQueryImgResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

