// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenechangenickname.proto

package com.cxy.oi.autogen;

public final class NetSceneChangeNicknameProto {
  private NetSceneChangeNicknameProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netscenechangenickname_NetSceneChangeNicknameReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netscenechangenickname_NetSceneChangeNicknameReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netscenechangenickname_NetSceneChangeNicknameResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netscenechangenickname_NetSceneChangeNicknameResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034netscenechangenickname.proto\022\026netscene" +
      "changenickname\"=\n\031NetSceneChangeNickname" +
      "Req\022\016\n\006usr_id\030\001 \001(\r\022\020\n\010nickname\030\002 \001(\t\")\n" +
      "\032NetSceneChangeNicknameResp\022\013\n\003nop\030\001 \001(\010" +
      "B3\n\022com.cxy.oi.autogenB\033NetSceneChangeNi" +
      "cknameProtoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_netscenechangenickname_NetSceneChangeNicknameReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netscenechangenickname_NetSceneChangeNicknameReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netscenechangenickname_NetSceneChangeNicknameReq_descriptor,
        new java.lang.String[] { "UsrId", "Nickname", });
    internal_static_netscenechangenickname_NetSceneChangeNicknameResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_netscenechangenickname_NetSceneChangeNicknameResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netscenechangenickname_NetSceneChangeNicknameResp_descriptor,
        new java.lang.String[] { "Nop", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
