// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenequeryimg.proto

package com.cxy.oi.autogen;

public interface NetSceneQueryImgReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netscenequeryimg.NetSceneQueryImgReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bytes img_bytes = 1;</code>
   * @return Whether the imgBytes field is set.
   */
  boolean hasImgBytes();
  /**
   * <code>required bytes img_bytes = 1;</code>
   * @return The imgBytes.
   */
  com.google.protobuf.ByteString getImgBytes();
}
