// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenequeryimg.proto

package com.cxy.oi.autogen;

public interface NetSceneQueryImgRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netscenequeryimg.NetSceneQueryImgResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .netscenequeryimg.NetSceneQueryImgResp.ItemType item_type = 1 [default = PLANT];</code>
   * @return Whether the itemType field is set.
   */
  boolean hasItemType();
  /**
   * <code>required .netscenequeryimg.NetSceneQueryImgResp.ItemType item_type = 1 [default = PLANT];</code>
   * @return The itemType.
   */
  com.cxy.oi.autogen.NetSceneQueryImgResp.ItemType getItemType();

  /**
   * <code>required string item_name = 2;</code>
   * @return Whether the itemName field is set.
   */
  boolean hasItemName();
  /**
   * <code>required string item_name = 2;</code>
   * @return The itemName.
   */
  java.lang.String getItemName();
  /**
   * <code>required string item_name = 2;</code>
   * @return The bytes for itemName.
   */
  com.google.protobuf.ByteString
      getItemNameBytes();

  /**
   * <code>required string item_desc = 3;</code>
   * @return Whether the itemDesc field is set.
   */
  boolean hasItemDesc();
  /**
   * <code>required string item_desc = 3;</code>
   * @return The itemDesc.
   */
  java.lang.String getItemDesc();
  /**
   * <code>required string item_desc = 3;</code>
   * @return The bytes for itemDesc.
   */
  com.google.protobuf.ByteString
      getItemDescBytes();
}
