// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenegethotsearch.proto

package com.cxy.oi.autogen;

/**
 * Protobuf type {@code netscenegethotsearch.NetSceneGetHotSearchResp}
 */
public final class NetSceneGetHotSearchResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:netscenegethotsearch.NetSceneGetHotSearchResp)
    NetSceneGetHotSearchRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetSceneGetHotSearchResp.newBuilder() to construct.
  private NetSceneGetHotSearchResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetSceneGetHotSearchResp() {
    hotSearchItems_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NetSceneGetHotSearchResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NetSceneGetHotSearchResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              hotSearchItems_ = new java.util.ArrayList<com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem>();
              mutable_bitField0_ |= 0x00000001;
            }
            hotSearchItems_.add(
                input.readMessage(com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        hotSearchItems_ = java.util.Collections.unmodifiableList(hotSearchItems_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cxy.oi.autogen.NetSceneGetHotSearchProto.internal_static_netscenegethotsearch_NetSceneGetHotSearchResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cxy.oi.autogen.NetSceneGetHotSearchProto.internal_static_netscenegethotsearch_NetSceneGetHotSearchResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cxy.oi.autogen.NetSceneGetHotSearchResp.class, com.cxy.oi.autogen.NetSceneGetHotSearchResp.Builder.class);
  }

  public interface HotSearchItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string item_name = 1;</code>
     * @return Whether the itemName field is set.
     */
    boolean hasItemName();
    /**
     * <code>optional string item_name = 1;</code>
     * @return The itemName.
     */
    java.lang.String getItemName();
    /**
     * <code>optional string item_name = 1;</code>
     * @return The bytes for itemName.
     */
    com.google.protobuf.ByteString
        getItemNameBytes();

    /**
     * <code>optional .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem.ItemType item_type = 2 [default = PLANT];</code>
     * @return Whether the itemType field is set.
     */
    boolean hasItemType();
    /**
     * <code>optional .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem.ItemType item_type = 2 [default = PLANT];</code>
     * @return The itemType.
     */
    com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType getItemType();

    /**
     * <code>optional uint32 heat = 3;</code>
     * @return Whether the heat field is set.
     */
    boolean hasHeat();
    /**
     * <code>optional uint32 heat = 3;</code>
     * @return The heat.
     */
    int getHeat();

    /**
     * <code>optional string item_desc = 4;</code>
     * @return Whether the itemDesc field is set.
     */
    boolean hasItemDesc();
    /**
     * <code>optional string item_desc = 4;</code>
     * @return The itemDesc.
     */
    java.lang.String getItemDesc();
    /**
     * <code>optional string item_desc = 4;</code>
     * @return The bytes for itemDesc.
     */
    com.google.protobuf.ByteString
        getItemDescBytes();
  }
  /**
   * Protobuf type {@code netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem}
   */
  public static final class HotSearchItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem)
      HotSearchItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HotSearchItem.newBuilder() to construct.
    private HotSearchItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HotSearchItem() {
      itemName_ = "";
      itemType_ = 0;
      itemDesc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HotSearchItem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HotSearchItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              itemName_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType value = com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                itemType_ = rawValue;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              heat_ = input.readUInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              itemDesc_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cxy.oi.autogen.NetSceneGetHotSearchProto.internal_static_netscenegethotsearch_NetSceneGetHotSearchResp_HotSearchItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cxy.oi.autogen.NetSceneGetHotSearchProto.internal_static_netscenegethotsearch_NetSceneGetHotSearchResp_HotSearchItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.class, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder.class);
    }

    /**
     * Protobuf enum {@code netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem.ItemType}
     */
    public enum ItemType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PLANT = 0;</code>
       */
      PLANT(0),
      /**
       * <code>ANIMAL = 1;</code>
       */
      ANIMAL(1),
      /**
       * <code>LANDMARK = 2;</code>
       */
      LANDMARK(2),
      ;

      /**
       * <code>PLANT = 0;</code>
       */
      public static final int PLANT_VALUE = 0;
      /**
       * <code>ANIMAL = 1;</code>
       */
      public static final int ANIMAL_VALUE = 1;
      /**
       * <code>LANDMARK = 2;</code>
       */
      public static final int LANDMARK_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ItemType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ItemType forNumber(int value) {
        switch (value) {
          case 0: return PLANT;
          case 1: return ANIMAL;
          case 2: return LANDMARK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ItemType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ItemType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ItemType>() {
              public ItemType findValueByNumber(int number) {
                return ItemType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.getDescriptor().getEnumTypes().get(0);
      }

      private static final ItemType[] VALUES = values();

      public static ItemType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ItemType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem.ItemType)
    }

    private int bitField0_;
    public static final int ITEM_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object itemName_;
    /**
     * <code>optional string item_name = 1;</code>
     * @return Whether the itemName field is set.
     */
    @java.lang.Override
    public boolean hasItemName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string item_name = 1;</code>
     * @return The itemName.
     */
    @java.lang.Override
    public java.lang.String getItemName() {
      java.lang.Object ref = itemName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string item_name = 1;</code>
     * @return The bytes for itemName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getItemNameBytes() {
      java.lang.Object ref = itemName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITEM_TYPE_FIELD_NUMBER = 2;
    private int itemType_;
    /**
     * <code>optional .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem.ItemType item_type = 2 [default = PLANT];</code>
     * @return Whether the itemType field is set.
     */
    @java.lang.Override public boolean hasItemType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem.ItemType item_type = 2 [default = PLANT];</code>
     * @return The itemType.
     */
    @java.lang.Override public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType getItemType() {
      @SuppressWarnings("deprecation")
      com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType result = com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType.valueOf(itemType_);
      return result == null ? com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType.PLANT : result;
    }

    public static final int HEAT_FIELD_NUMBER = 3;
    private int heat_;
    /**
     * <code>optional uint32 heat = 3;</code>
     * @return Whether the heat field is set.
     */
    @java.lang.Override
    public boolean hasHeat() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 heat = 3;</code>
     * @return The heat.
     */
    @java.lang.Override
    public int getHeat() {
      return heat_;
    }

    public static final int ITEM_DESC_FIELD_NUMBER = 4;
    private volatile java.lang.Object itemDesc_;
    /**
     * <code>optional string item_desc = 4;</code>
     * @return Whether the itemDesc field is set.
     */
    @java.lang.Override
    public boolean hasItemDesc() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string item_desc = 4;</code>
     * @return The itemDesc.
     */
    @java.lang.Override
    public java.lang.String getItemDesc() {
      java.lang.Object ref = itemDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemDesc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string item_desc = 4;</code>
     * @return The bytes for itemDesc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getItemDescBytes() {
      java.lang.Object ref = itemDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, itemName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, itemType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, heat_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, itemDesc_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, itemName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, itemType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, heat_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, itemDesc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem)) {
        return super.equals(obj);
      }
      com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem other = (com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem) obj;

      if (hasItemName() != other.hasItemName()) return false;
      if (hasItemName()) {
        if (!getItemName()
            .equals(other.getItemName())) return false;
      }
      if (hasItemType() != other.hasItemType()) return false;
      if (hasItemType()) {
        if (itemType_ != other.itemType_) return false;
      }
      if (hasHeat() != other.hasHeat()) return false;
      if (hasHeat()) {
        if (getHeat()
            != other.getHeat()) return false;
      }
      if (hasItemDesc() != other.hasItemDesc()) return false;
      if (hasItemDesc()) {
        if (!getItemDesc()
            .equals(other.getItemDesc())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasItemName()) {
        hash = (37 * hash) + ITEM_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getItemName().hashCode();
      }
      if (hasItemType()) {
        hash = (37 * hash) + ITEM_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + itemType_;
      }
      if (hasHeat()) {
        hash = (37 * hash) + HEAT_FIELD_NUMBER;
        hash = (53 * hash) + getHeat();
      }
      if (hasItemDesc()) {
        hash = (37 * hash) + ITEM_DESC_FIELD_NUMBER;
        hash = (53 * hash) + getItemDesc().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem)
        com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cxy.oi.autogen.NetSceneGetHotSearchProto.internal_static_netscenegethotsearch_NetSceneGetHotSearchResp_HotSearchItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cxy.oi.autogen.NetSceneGetHotSearchProto.internal_static_netscenegethotsearch_NetSceneGetHotSearchResp_HotSearchItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.class, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder.class);
      }

      // Construct using com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        itemName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        itemType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        heat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        itemDesc_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cxy.oi.autogen.NetSceneGetHotSearchProto.internal_static_netscenegethotsearch_NetSceneGetHotSearchResp_HotSearchItem_descriptor;
      }

      @java.lang.Override
      public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem getDefaultInstanceForType() {
        return com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.getDefaultInstance();
      }

      @java.lang.Override
      public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem build() {
        com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem buildPartial() {
        com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem result = new com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemName_ = itemName_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.itemType_ = itemType_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.heat_ = heat_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.itemDesc_ = itemDesc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem) {
          return mergeFrom((com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem other) {
        if (other == com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.getDefaultInstance()) return this;
        if (other.hasItemName()) {
          bitField0_ |= 0x00000001;
          itemName_ = other.itemName_;
          onChanged();
        }
        if (other.hasItemType()) {
          setItemType(other.getItemType());
        }
        if (other.hasHeat()) {
          setHeat(other.getHeat());
        }
        if (other.hasItemDesc()) {
          bitField0_ |= 0x00000008;
          itemDesc_ = other.itemDesc_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object itemName_ = "";
      /**
       * <code>optional string item_name = 1;</code>
       * @return Whether the itemName field is set.
       */
      public boolean hasItemName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string item_name = 1;</code>
       * @return The itemName.
       */
      public java.lang.String getItemName() {
        java.lang.Object ref = itemName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            itemName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string item_name = 1;</code>
       * @return The bytes for itemName.
       */
      public com.google.protobuf.ByteString
          getItemNameBytes() {
        java.lang.Object ref = itemName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string item_name = 1;</code>
       * @param value The itemName to set.
       * @return This builder for chaining.
       */
      public Builder setItemName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        itemName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string item_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemName_ = getDefaultInstance().getItemName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string item_name = 1;</code>
       * @param value The bytes for itemName to set.
       * @return This builder for chaining.
       */
      public Builder setItemNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        itemName_ = value;
        onChanged();
        return this;
      }

      private int itemType_ = 0;
      /**
       * <code>optional .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem.ItemType item_type = 2 [default = PLANT];</code>
       * @return Whether the itemType field is set.
       */
      @java.lang.Override public boolean hasItemType() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem.ItemType item_type = 2 [default = PLANT];</code>
       * @return The itemType.
       */
      @java.lang.Override
      public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType getItemType() {
        @SuppressWarnings("deprecation")
        com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType result = com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType.valueOf(itemType_);
        return result == null ? com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType.PLANT : result;
      }
      /**
       * <code>optional .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem.ItemType item_type = 2 [default = PLANT];</code>
       * @param value The itemType to set.
       * @return This builder for chaining.
       */
      public Builder setItemType(com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.ItemType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        itemType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem.ItemType item_type = 2 [default = PLANT];</code>
       * @return This builder for chaining.
       */
      public Builder clearItemType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        itemType_ = 0;
        onChanged();
        return this;
      }

      private int heat_ ;
      /**
       * <code>optional uint32 heat = 3;</code>
       * @return Whether the heat field is set.
       */
      @java.lang.Override
      public boolean hasHeat() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint32 heat = 3;</code>
       * @return The heat.
       */
      @java.lang.Override
      public int getHeat() {
        return heat_;
      }
      /**
       * <code>optional uint32 heat = 3;</code>
       * @param value The heat to set.
       * @return This builder for chaining.
       */
      public Builder setHeat(int value) {
        bitField0_ |= 0x00000004;
        heat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 heat = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeat() {
        bitField0_ = (bitField0_ & ~0x00000004);
        heat_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object itemDesc_ = "";
      /**
       * <code>optional string item_desc = 4;</code>
       * @return Whether the itemDesc field is set.
       */
      public boolean hasItemDesc() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string item_desc = 4;</code>
       * @return The itemDesc.
       */
      public java.lang.String getItemDesc() {
        java.lang.Object ref = itemDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            itemDesc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string item_desc = 4;</code>
       * @return The bytes for itemDesc.
       */
      public com.google.protobuf.ByteString
          getItemDescBytes() {
        java.lang.Object ref = itemDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string item_desc = 4;</code>
       * @param value The itemDesc to set.
       * @return This builder for chaining.
       */
      public Builder setItemDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        itemDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string item_desc = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemDesc() {
        bitField0_ = (bitField0_ & ~0x00000008);
        itemDesc_ = getDefaultInstance().getItemDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string item_desc = 4;</code>
       * @param value The bytes for itemDesc to set.
       * @return This builder for chaining.
       */
      public Builder setItemDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        itemDesc_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem)
    }

    // @@protoc_insertion_point(class_scope:netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem)
    private static final com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem();
    }

    public static com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HotSearchItem>
        PARSER = new com.google.protobuf.AbstractParser<HotSearchItem>() {
      @java.lang.Override
      public HotSearchItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HotSearchItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HotSearchItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HotSearchItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int HOT_SEARCH_ITEMS_FIELD_NUMBER = 1;
  private java.util.List<com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem> hotSearchItems_;
  /**
   * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem> getHotSearchItemsList() {
    return hotSearchItems_;
  }
  /**
   * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItemOrBuilder> 
      getHotSearchItemsOrBuilderList() {
    return hotSearchItems_;
  }
  /**
   * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
   */
  @java.lang.Override
  public int getHotSearchItemsCount() {
    return hotSearchItems_.size();
  }
  /**
   * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
   */
  @java.lang.Override
  public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem getHotSearchItems(int index) {
    return hotSearchItems_.get(index);
  }
  /**
   * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
   */
  @java.lang.Override
  public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItemOrBuilder getHotSearchItemsOrBuilder(
      int index) {
    return hotSearchItems_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < hotSearchItems_.size(); i++) {
      output.writeMessage(1, hotSearchItems_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < hotSearchItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, hotSearchItems_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cxy.oi.autogen.NetSceneGetHotSearchResp)) {
      return super.equals(obj);
    }
    com.cxy.oi.autogen.NetSceneGetHotSearchResp other = (com.cxy.oi.autogen.NetSceneGetHotSearchResp) obj;

    if (!getHotSearchItemsList()
        .equals(other.getHotSearchItemsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHotSearchItemsCount() > 0) {
      hash = (37 * hash) + HOT_SEARCH_ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getHotSearchItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cxy.oi.autogen.NetSceneGetHotSearchResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code netscenegethotsearch.NetSceneGetHotSearchResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:netscenegethotsearch.NetSceneGetHotSearchResp)
      com.cxy.oi.autogen.NetSceneGetHotSearchRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cxy.oi.autogen.NetSceneGetHotSearchProto.internal_static_netscenegethotsearch_NetSceneGetHotSearchResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cxy.oi.autogen.NetSceneGetHotSearchProto.internal_static_netscenegethotsearch_NetSceneGetHotSearchResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cxy.oi.autogen.NetSceneGetHotSearchResp.class, com.cxy.oi.autogen.NetSceneGetHotSearchResp.Builder.class);
    }

    // Construct using com.cxy.oi.autogen.NetSceneGetHotSearchResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHotSearchItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (hotSearchItemsBuilder_ == null) {
        hotSearchItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        hotSearchItemsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cxy.oi.autogen.NetSceneGetHotSearchProto.internal_static_netscenegethotsearch_NetSceneGetHotSearchResp_descriptor;
    }

    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneGetHotSearchResp getDefaultInstanceForType() {
      return com.cxy.oi.autogen.NetSceneGetHotSearchResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneGetHotSearchResp build() {
      com.cxy.oi.autogen.NetSceneGetHotSearchResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cxy.oi.autogen.NetSceneGetHotSearchResp buildPartial() {
      com.cxy.oi.autogen.NetSceneGetHotSearchResp result = new com.cxy.oi.autogen.NetSceneGetHotSearchResp(this);
      int from_bitField0_ = bitField0_;
      if (hotSearchItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          hotSearchItems_ = java.util.Collections.unmodifiableList(hotSearchItems_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.hotSearchItems_ = hotSearchItems_;
      } else {
        result.hotSearchItems_ = hotSearchItemsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cxy.oi.autogen.NetSceneGetHotSearchResp) {
        return mergeFrom((com.cxy.oi.autogen.NetSceneGetHotSearchResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cxy.oi.autogen.NetSceneGetHotSearchResp other) {
      if (other == com.cxy.oi.autogen.NetSceneGetHotSearchResp.getDefaultInstance()) return this;
      if (hotSearchItemsBuilder_ == null) {
        if (!other.hotSearchItems_.isEmpty()) {
          if (hotSearchItems_.isEmpty()) {
            hotSearchItems_ = other.hotSearchItems_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHotSearchItemsIsMutable();
            hotSearchItems_.addAll(other.hotSearchItems_);
          }
          onChanged();
        }
      } else {
        if (!other.hotSearchItems_.isEmpty()) {
          if (hotSearchItemsBuilder_.isEmpty()) {
            hotSearchItemsBuilder_.dispose();
            hotSearchItemsBuilder_ = null;
            hotSearchItems_ = other.hotSearchItems_;
            bitField0_ = (bitField0_ & ~0x00000001);
            hotSearchItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHotSearchItemsFieldBuilder() : null;
          } else {
            hotSearchItemsBuilder_.addAllMessages(other.hotSearchItems_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cxy.oi.autogen.NetSceneGetHotSearchResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cxy.oi.autogen.NetSceneGetHotSearchResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem> hotSearchItems_ =
      java.util.Collections.emptyList();
    private void ensureHotSearchItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        hotSearchItems_ = new java.util.ArrayList<com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem>(hotSearchItems_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItemOrBuilder> hotSearchItemsBuilder_;

    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public java.util.List<com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem> getHotSearchItemsList() {
      if (hotSearchItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(hotSearchItems_);
      } else {
        return hotSearchItemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public int getHotSearchItemsCount() {
      if (hotSearchItemsBuilder_ == null) {
        return hotSearchItems_.size();
      } else {
        return hotSearchItemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem getHotSearchItems(int index) {
      if (hotSearchItemsBuilder_ == null) {
        return hotSearchItems_.get(index);
      } else {
        return hotSearchItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public Builder setHotSearchItems(
        int index, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem value) {
      if (hotSearchItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHotSearchItemsIsMutable();
        hotSearchItems_.set(index, value);
        onChanged();
      } else {
        hotSearchItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public Builder setHotSearchItems(
        int index, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder builderForValue) {
      if (hotSearchItemsBuilder_ == null) {
        ensureHotSearchItemsIsMutable();
        hotSearchItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        hotSearchItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public Builder addHotSearchItems(com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem value) {
      if (hotSearchItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHotSearchItemsIsMutable();
        hotSearchItems_.add(value);
        onChanged();
      } else {
        hotSearchItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public Builder addHotSearchItems(
        int index, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem value) {
      if (hotSearchItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHotSearchItemsIsMutable();
        hotSearchItems_.add(index, value);
        onChanged();
      } else {
        hotSearchItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public Builder addHotSearchItems(
        com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder builderForValue) {
      if (hotSearchItemsBuilder_ == null) {
        ensureHotSearchItemsIsMutable();
        hotSearchItems_.add(builderForValue.build());
        onChanged();
      } else {
        hotSearchItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public Builder addHotSearchItems(
        int index, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder builderForValue) {
      if (hotSearchItemsBuilder_ == null) {
        ensureHotSearchItemsIsMutable();
        hotSearchItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        hotSearchItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public Builder addAllHotSearchItems(
        java.lang.Iterable<? extends com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem> values) {
      if (hotSearchItemsBuilder_ == null) {
        ensureHotSearchItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hotSearchItems_);
        onChanged();
      } else {
        hotSearchItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public Builder clearHotSearchItems() {
      if (hotSearchItemsBuilder_ == null) {
        hotSearchItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        hotSearchItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public Builder removeHotSearchItems(int index) {
      if (hotSearchItemsBuilder_ == null) {
        ensureHotSearchItemsIsMutable();
        hotSearchItems_.remove(index);
        onChanged();
      } else {
        hotSearchItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder getHotSearchItemsBuilder(
        int index) {
      return getHotSearchItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItemOrBuilder getHotSearchItemsOrBuilder(
        int index) {
      if (hotSearchItemsBuilder_ == null) {
        return hotSearchItems_.get(index);  } else {
        return hotSearchItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public java.util.List<? extends com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItemOrBuilder> 
         getHotSearchItemsOrBuilderList() {
      if (hotSearchItemsBuilder_ != null) {
        return hotSearchItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(hotSearchItems_);
      }
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder addHotSearchItemsBuilder() {
      return getHotSearchItemsFieldBuilder().addBuilder(
          com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.getDefaultInstance());
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder addHotSearchItemsBuilder(
        int index) {
      return getHotSearchItemsFieldBuilder().addBuilder(
          index, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.getDefaultInstance());
    }
    /**
     * <code>repeated .netscenegethotsearch.NetSceneGetHotSearchResp.HotSearchItem hot_search_items = 1;</code>
     */
    public java.util.List<com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder> 
         getHotSearchItemsBuilderList() {
      return getHotSearchItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItemOrBuilder> 
        getHotSearchItemsFieldBuilder() {
      if (hotSearchItemsBuilder_ == null) {
        hotSearchItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItem.Builder, com.cxy.oi.autogen.NetSceneGetHotSearchResp.HotSearchItemOrBuilder>(
                hotSearchItems_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        hotSearchItems_ = null;
      }
      return hotSearchItemsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:netscenegethotsearch.NetSceneGetHotSearchResp)
  }

  // @@protoc_insertion_point(class_scope:netscenegethotsearch.NetSceneGetHotSearchResp)
  private static final com.cxy.oi.autogen.NetSceneGetHotSearchResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cxy.oi.autogen.NetSceneGetHotSearchResp();
  }

  public static com.cxy.oi.autogen.NetSceneGetHotSearchResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<NetSceneGetHotSearchResp>
      PARSER = new com.google.protobuf.AbstractParser<NetSceneGetHotSearchResp>() {
    @java.lang.Override
    public NetSceneGetHotSearchResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NetSceneGetHotSearchResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NetSceneGetHotSearchResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetSceneGetHotSearchResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cxy.oi.autogen.NetSceneGetHotSearchResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

