// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netsceneuploadavatar.proto

package com.cxy.oi.autogen;

public interface NetSceneUploadAvatarRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netsceneuploadavatar.NetSceneUploadAvatarResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * padding
   * </pre>
   *
   * <code>optional bool nop = 1;</code>
   * @return Whether the nop field is set.
   */
  boolean hasNop();
  /**
   * <pre>
   * padding
   * </pre>
   *
   * <code>optional bool nop = 1;</code>
   * @return The nop.
   */
  boolean getNop();
}
