// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netscenechangenickname.proto

package com.cxy.oi.autogen;

public interface NetSceneChangeNicknameRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netscenechangenickname.NetSceneChangeNicknameResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * no req body, this is for padding.
   * </pre>
   *
   * <code>optional bool nop = 1;</code>
   * @return Whether the nop field is set.
   */
  boolean hasNop();
  /**
   * <pre>
   * no req body, this is for padding.
   * </pre>
   *
   * <code>optional bool nop = 1;</code>
   * @return The nop.
   */
  boolean getNop();
}
